version: '3.8'

services:
  dms-fe:
    image: liinhhnt/dms-fe
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: npm run dev -- --host 0.0.0.0
